# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
---
# https://nocodb.com/docs/self-hosting/installation/docker
services:
  nocodb:
    image: nocodb/nocodb:latest
    container_name: NocoDB
    ports: ["8080:8080"]  # http://localhost:8080/
    volumes:
      - type: bind
        source: ./data
        target: /usr/app/data/
