# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
---
services:
  redis:
    image: redis:7.4
    container_name: Redis
    ports: ["6379:6379"]
